from __future__ import annotations
from abc import ABC, abstractmethod
from common.app_common.models import PipelineConfig, PipelineState

class RuntimeAdapter(ABC):
    @abstractmethod
    async def start_live_pipeline(self, config: PipelineConfig, state: PipelineState) -> tuple[str, str]: ...
    @abstractmethod
    async def stop_live_pipeline(self, config: PipelineConfig, state: PipelineState) -> None: ...
    @abstractmethod
    async def restart_live_pipeline(self, config: PipelineConfig, state: PipelineState) -> tuple[str, str]: ...
    @abstractmethod
    async def get_logs(self, container_name: str, *, tail: int = 200) -> str: ...
    @abstractmethod
    async def is_running(self, container_name: str) -> bool: ...
